# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.comuniVenAcq.CondizioniDiVenditaParams', 'it.cope.thip.base.comuniVenAcq.YCondizioniDiVenditaParams', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.generaleVE.CondizioniDiVendita', 'it.cope.thip.vendite.generaleVE.YCondizioniDiVendita', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.generaleVE.RicercaCondizioniDiVendita', 'it.cope.thip.vendite.generaleVE.YRicercaCondizioniDiVendita', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.ordineVE.OrdineVenditaRigaSec', 'it.cope.thip.vendite.ordineVE.YOrdineVenditaRigaSec', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.offerteCliente.OffertaClienteRigaPrm', 'it.cope.thip.vendite.offerteCliente.YOffertaClienteRigaPrm', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.offerteCliente.OffertaClienteRigaSec', 'it.cope.thip.vendite.offerteCliente.YOffertaClienteRigaSec', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.DocumentoVenRigaPrm', 'it.cope.thip.vendite.documentoVE.YDocumentoVenRigaPrm', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.DocumentoVenRigaSec', 'it.cope.thip.vendite.documentoVE.YDocumentoVenRigaSec', '0', 'N');